# name: Code Coverage Check

# on:
#   push:
#     branches:
#       - main

# jobs:
#   code_coverage:
#     name: Code Coverage
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9  # Choose the appropriate Python version

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install django
#           pip install coverage pytest

#       - name: Run tests with coverage
#         run: |
#           coverage run -m unittest discover .

#       - name: coverage Report
#         run: |
#            coverage report -m
